version: '3'
services:
  postgres:
    container_name: db
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - ./data/postgres:/postgresql/data
  api:
    build: ./
    container_name: api
    env_file:
      - .env.prod
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app