name: PR and Push - Build and Test

on:
  [pull_request, push]

jobs:
  pr-pull-build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Run tests with coverage
        run: jest --runInBand --color --coverage