name: PR and Push - Build and Test

on:
  [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Check linter and prettier
        run: npm run check
  jest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_DB: efa_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run tests
        run: npx prisma db push && npx jest --runInBand --coverage --color