name: PR and Push - Build and Test

on:
  [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Check linter and prettier
        run: npm run check
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # NEED TO SET THIS UP IN GitHub
        - name: Check out code
          uses: actions/checkout@v2
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          witch:
            context: ./
            push: true
            tags: musosy/efa:latest
